# Generated by Django 2.2 on 2019-10-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Placement_Brochure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brochure', models.FileField(upload_to='placement/')),
            ],
        ),
        migrations.CreateModel(
            name='Placement_Invitaton_For_Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitation', models.FileField(upload_to='placement/')),
            ],
        ),
    ]
