# Generated by Django 2.2 on 2019-10-25 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='biotechnology_dept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='department/BT/image/')),
                ('detail', models.FileField(upload_to='department/BT/data/')),
            ],
        ),
        migrations.CreateModel(
            name='chemical_dept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='department/CH/image/')),
                ('detail', models.FileField(upload_to='department/CH/data/')),
            ],
        ),
        migrations.CreateModel(
            name='chemistry_dept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='department/CHE/image/')),
                ('detail', models.FileField(upload_to='department/CHE/data/')),
            ],
        ),
        migrations.CreateModel(
            name='civil_dept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='department/CV/image/')),
                ('detail', models.FileField(upload_to='department/CV/data/')),
            ],
        ),
        migrations.CreateModel(
            name='computer_science_dept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='department/CS/image/')),
                ('detail', models.FileField(upload_to='department/CS/data/')),
            ],
        ),
        migrations.CreateModel(
            name='electrical_and_electronics_dept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='department/EEE/image/')),
                ('detail', models.FileField(upload_to='department/EEE/data/')),
            ],
        ),
        migrations.CreateModel(
            name='electronics_and_communication_dept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='department/EC/image/')),
                ('detail', models.FileField(upload_to='department/EC/data/')),
            ],
        ),
        migrations.CreateModel(
            name='environmental_dept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='department/ENV/image/')),
                ('detail', models.FileField(upload_to='department/ENV/data/')),
            ],
        ),
        migrations.CreateModel(
            name='information_science_dept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='department/IS/image/')),
                ('detail', models.FileField(upload_to='department/IS/data/')),
            ],
        ),
        migrations.CreateModel(
            name='mathematics_dept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='department/MAT/image/')),
                ('detail', models.FileField(upload_to='department/MAT/data/')),
            ],
        ),
        migrations.CreateModel(
            name='mca_dept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='department/MCA/image/')),
                ('detail', models.FileField(upload_to='department/MCA/data/')),
            ],
        ),
        migrations.CreateModel(
            name='mechanical_dept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='department/ME/image/')),
                ('detail', models.FileField(upload_to='department/ME/data/')),
            ],
        ),
        migrations.CreateModel(
            name='physics_dept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='department/PHY/image/')),
                ('detail', models.FileField(upload_to='department/PHY/data/')),
            ],
        ),
        migrations.CreateModel(
            name='textile_dept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='department/TX/image/')),
                ('detail', models.FileField(upload_to='department/TX/data/')),
            ],
        ),
    ]
