# Generated by Django 2.2 on 2019-10-25 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_civil_depatment_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='biotechnology_dept_gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='department/gallery/CV/')),
            ],
        ),
        migrations.CreateModel(
            name='chemical_dept_gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='department/gallery/CV/')),
            ],
        ),
        migrations.CreateModel(
            name='chemistry_dept_gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='department/gallery/CV/')),
            ],
        ),
        migrations.CreateModel(
            name='computer_science_dept_gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='department/gallery/CV/')),
            ],
        ),
        migrations.CreateModel(
            name='electrical_and_electronics_gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='department/gallery/CV/')),
            ],
        ),
        migrations.CreateModel(
            name='electronics_and_communication_gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='department/gallery/CV/')),
            ],
        ),
        migrations.CreateModel(
            name='environmental_dept_gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='department/gallery/CV/')),
            ],
        ),
        migrations.CreateModel(
            name='information_science_dept_gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='department/gallery/CV/')),
            ],
        ),
        migrations.CreateModel(
            name='mathematics_dept_gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='department/gallery/CV/')),
            ],
        ),
        migrations.CreateModel(
            name='mca_dept_gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='department/gallery/CV/')),
            ],
        ),
        migrations.CreateModel(
            name='mechanical_dept_gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='department/gallery/CV/')),
            ],
        ),
        migrations.CreateModel(
            name='physics_dept_gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='department/gallery/CV/')),
            ],
        ),
        migrations.CreateModel(
            name='textile_dept_gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='department/gallery/CV/')),
            ],
        ),
    ]
