# Generated by Django 3.0.6 on 2020-05-19 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_biotechnology_dept_gallery_chemical_dept_gallery_chemistry_dept_gallery_computer_science_dept_galler'),
    ]

    operations = [
        migrations.CreateModel(
            name='computer_science_dept_achievements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_description', models.TextField()),
                ('achievement_type', models.CharField(choices=[('STUDENT', 'Student Achievement'), ('STAFF', 'Staff Achievement')], default='STAFF', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='computer_science_dept_activities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('activity_name', models.CharField(max_length=200)),
                ('activity_description', models.TextField()),
                ('activity_type', models.CharField(choices=[('RE', 'Regular Event'), ('STC', 'Short-term Course')], default='RE', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='computer_science_dept_lab_facilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('qty', models.IntegerField()),
                ('config_specs', models.TextField()),
                ('softwares', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='computer_science_dept_major_equipments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_description', models.TextField()),
            ],
        ),
    ]
