# Generated by Django 3.0.6 on 2020-05-20 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0004_computer_science_dept_achievements_computer_science_dept_activities_computer_science_dept_lab_facili'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer_science_dept_gallery',
            name='image',
            field=models.ImageField(upload_to='department/gallery/PhotoGallery/'),
        ),
    ]
