# Generated by Django 3.0.6 on 2020-05-22 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0005_auto_20200520_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='computer_science_dept_timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(choices=[('B.E.', 'BE'), ('M.Tech', 'MT')], default='BE', max_length=100)),
                ('semester', models.TextField()),
                ('section', models.CharField(max_length=1)),
                ('timetable', models.FileField(upload_to='department/CS/data/')),
            ],
        ),
    ]
