# Generated by Django 3.0.6 on 2020-05-22 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0006_computer_science_dept_timetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer_science_dept_timetable',
            name='timetable',
            field=models.FileField(upload_to='department/CS/data/timetable/'),
        ),
    ]
