# Generated by Django 3.0.6 on 2020-05-22 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0007_auto_20200523_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer_science_dept_timetable',
            name='semester',
            field=models.IntegerField(),
        ),
    ]
