# Generated by Django 2.2 on 2020-05-23 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0009_auto_20200523_0024'),
    ]

    operations = [
        migrations.CreateModel(
            name='computer_science_dept_events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('events', models.FileField(upload_to='department/CS/data/events/')),
            ],
        ),
    ]
