# Generated by Django 2.2 on 2020-05-23 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0010_computer_science_dept_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer_science_dept_events',
            name='semester',
            field=models.CharField(default='even', max_length=10),
            preserve_default=False,
        ),
    ]
