# Generated by Django 2.2 on 2020-05-23 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0011_computer_science_dept_events_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer_science_dept_events',
            name='name',
            field=models.CharField(default='2019', max_length=30),
            preserve_default=False,
        ),
    ]
