# Generated by Django 3.0.6 on 2020-05-23 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0011_auto_20200524_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer_science_dept_research_scholars',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
