# Generated by Django 2.2 on 2020-05-23 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0012_computer_science_dept_events_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='computer_science_dept_classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.FileField(upload_to='department/CS/data/classroom/')),
            ],
        ),
    ]
