# Generated by Django 3.0.6 on 2020-05-23 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0012_auto_20200524_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer_science_dept_research_scholars',
            name='department',
            field=models.CharField(max_length=100),
        ),
    ]
