# Generated by Django 2.2 on 2020-05-23 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0013_computer_science_dept_classroom'),
        ('department', '0013_auto_20200524_0215'),
    ]

    operations = [
    ]
