# Generated by Django 2.2 on 2020-05-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0014_merge_20200524_0342'),
    ]

    operations = [
        migrations.AddField(
            model_name='environmental_dept',
            name='sno',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
