# Generated by Django 2.2 on 2020-05-24 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0015_environmental_dept_sno'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer_science_dept',
            name='sno',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
