# Generated by Django 2.2 on 2020-05-24 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0017_auto_20200525_0147'),
    ]

    operations = [
        migrations.CreateModel(
            name='computer_science_dept_laboratory_facilities_gallary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='department/gallery/CS/laboratory/')),
            ],
        ),
    ]
