# Generated by Django 3.0.6 on 2020-05-29 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0018_computer_science_dept_laboratory_facilities_gallary'),
    ]

    operations = [
        migrations.CreateModel(
            name='computer_science_dept_book_chapters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_no', models.IntegerField()),
                ('name_of_book_chapter', models.CharField(max_length=500)),
                ('names_of_authors', models.CharField(max_length=500)),
                ('year_of_pub', models.IntegerField()),
                ('name_of_pub', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='computer_science_dept_publications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_faculty', models.CharField(max_length=100)),
                ('y15', models.IntegerField(blank=True, null=True)),
                ('y16', models.IntegerField(blank=True, null=True)),
                ('y17', models.IntegerField(blank=True, null=True)),
                ('y18', models.IntegerField(blank=True, null=True)),
                ('y19', models.IntegerField(blank=True, null=True)),
                ('national_or_inter', models.CharField(max_length=13)),
                ('indexing', models.CharField(blank=True, max_length=500, null=True)),
                ('citations', models.IntegerField(blank=True, null=True)),
                ('impact_factor', models.CharField(blank=True, max_length=80, null=True)),
                ('i10_index', models.IntegerField(blank=True, null=True)),
                ('h_index', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
