# Generated by Django 3.0.6 on 2020-06-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0021_auto_20200618_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer_science_dept_accreditation',
            name='designation',
            field=models.TextField(blank=True),
        ),
    ]
