# Generated by Django 3.0.6 on 2020-06-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0022_auto_20200618_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer_science_dept',
            name='staff_type',
            field=models.CharField(choices=[('HOD', 'Head Of Department'), ('FACULTY', 'Faculty Member'), ('TECHNICAL', 'Technical Staff'), ('SUPPORTING', 'Supporting Staff')], default='FACULTY', max_length=100),
        ),
        migrations.AlterField(
            model_name='computer_science_dept_accreditation',
            name='member_type',
            field=models.CharField(choices=[('PAC', 'Program Assessment Committee (PAC)'), ('DAB', 'Department Advisory Board (DAB)')], default='DAB', max_length=100),
        ),
    ]
