# Generated by Django 3.0.6 on 2020-06-18 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0023_auto_20200618_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer_science_dept',
            name='detail',
            field=models.FileField(blank='True', upload_to='department/CS/data/'),
        ),
    ]
