# Generated by Django 3.0.6 on 2020-06-20 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0024_auto_20200618_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='chemistry_dept_achievements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_description', models.TextField()),
                ('achievement_type', models.CharField(choices=[('STUDENT', 'Student Achievement'), ('STAFF', 'Staff Achievement')], default='STAFF', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='chemistry_dept_activities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('activity_name', models.CharField(max_length=200)),
                ('activity_description', models.TextField()),
                ('activity_type', models.CharField(choices=[('RE', 'Regular Event'), ('STC', 'Short-term Course')], default='RE', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='chemistry_dept_book_chapters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_no', models.IntegerField()),
                ('name_of_book_chapter', models.CharField(max_length=500)),
                ('names_of_authors', models.CharField(max_length=500)),
                ('year_of_pub', models.IntegerField()),
                ('name_of_pub', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='chemistry_dept_classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.FileField(upload_to='department/CS/data/classroom/')),
            ],
        ),
        migrations.CreateModel(
            name='chemistry_dept_events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('events', models.FileField(upload_to='department/CS/data/events/')),
                ('semester', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='chemistry_dept_lab_facilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('qty', models.IntegerField()),
                ('config_specs', models.TextField()),
                ('softwares', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='chemistry_dept_laboratory_facilities_gallary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='department/gallery/CS/laboratory/')),
            ],
        ),
        migrations.CreateModel(
            name='chemistry_dept_major_equipments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='chemistry_dept_publications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_faculty', models.CharField(max_length=100)),
                ('y15', models.IntegerField(blank=True, null=True)),
                ('y16', models.IntegerField(blank=True, null=True)),
                ('y17', models.IntegerField(blank=True, null=True)),
                ('y18', models.IntegerField(blank=True, null=True)),
                ('y19', models.IntegerField(blank=True, null=True)),
                ('national_or_inter', models.CharField(max_length=13)),
                ('indexing', models.CharField(blank=True, max_length=500, null=True)),
                ('citations', models.IntegerField(blank=True, null=True)),
                ('impact_factor', models.CharField(blank=True, max_length=80, null=True)),
                ('i10_index', models.IntegerField(blank=True, null=True)),
                ('h_index', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='chemistry_dept_research_guide',
            fields=[
                ('sno', models.IntegerField(primary_key=True, serialize=False)),
                ('guide_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='chemistry_dept_timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(choices=[('BE', 'B.E.'), ('MT', 'M.Tech')], default='BE', max_length=100)),
                ('semester', models.IntegerField()),
                ('section', models.CharField(max_length=1)),
                ('timetable', models.FileField(upload_to='department/CS/data/timetable/')),
            ],
        ),
        migrations.CreateModel(
            name='civil_dept_achievements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_description', models.TextField()),
                ('achievement_type', models.CharField(choices=[('STUDENT', 'Student Achievement'), ('STAFF', 'Staff Achievement')], default='STAFF', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='civil_dept_activities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('activity_name', models.CharField(max_length=200)),
                ('activity_description', models.TextField()),
                ('activity_type', models.CharField(choices=[('RE', 'Regular Event'), ('STC', 'Short-term Course')], default='RE', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='civil_dept_book_chapters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_no', models.IntegerField()),
                ('name_of_book_chapter', models.CharField(max_length=500)),
                ('names_of_authors', models.CharField(max_length=500)),
                ('year_of_pub', models.IntegerField()),
                ('name_of_pub', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='civil_dept_classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.FileField(upload_to='department/CS/data/classroom/')),
            ],
        ),
        migrations.CreateModel(
            name='civil_dept_events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('events', models.FileField(upload_to='department/CS/data/events/')),
                ('semester', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='civil_dept_lab_facilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('qty', models.IntegerField()),
                ('config_specs', models.TextField()),
                ('softwares', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='civil_dept_laboratory_facilities_gallary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='department/gallery/CS/laboratory/')),
            ],
        ),
        migrations.CreateModel(
            name='civil_dept_major_equipments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='civil_dept_publications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_faculty', models.CharField(max_length=100)),
                ('y15', models.IntegerField(blank=True, null=True)),
                ('y16', models.IntegerField(blank=True, null=True)),
                ('y17', models.IntegerField(blank=True, null=True)),
                ('y18', models.IntegerField(blank=True, null=True)),
                ('y19', models.IntegerField(blank=True, null=True)),
                ('national_or_inter', models.CharField(max_length=13)),
                ('indexing', models.CharField(blank=True, max_length=500, null=True)),
                ('citations', models.IntegerField(blank=True, null=True)),
                ('impact_factor', models.CharField(blank=True, max_length=80, null=True)),
                ('i10_index', models.IntegerField(blank=True, null=True)),
                ('h_index', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='civil_dept_research_guide',
            fields=[
                ('sno', models.IntegerField(primary_key=True, serialize=False)),
                ('guide_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='civil_dept_timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(choices=[('BE', 'B.E.'), ('MT', 'M.Tech')], default='BE', max_length=100)),
                ('semester', models.IntegerField()),
                ('section', models.CharField(max_length=1)),
                ('timetable', models.FileField(upload_to='department/CS/data/timetable/')),
            ],
        ),
        migrations.CreateModel(
            name='mathematics_dept_achievements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_description', models.TextField()),
                ('achievement_type', models.CharField(choices=[('STUDENT', 'Student Achievement'), ('STAFF', 'Staff Achievement')], default='STAFF', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='mathematics_dept_activities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('activity_name', models.CharField(max_length=200)),
                ('activity_description', models.TextField()),
                ('activity_type', models.CharField(choices=[('RE', 'Regular Event'), ('STC', 'Short-term Course')], default='RE', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='mathematics_dept_book_chapters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_no', models.IntegerField()),
                ('name_of_book_chapter', models.CharField(max_length=500)),
                ('names_of_authors', models.CharField(max_length=500)),
                ('year_of_pub', models.IntegerField()),
                ('name_of_pub', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='mathematics_dept_classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.FileField(upload_to='department/CS/data/classroom/')),
            ],
        ),
        migrations.CreateModel(
            name='mathematics_dept_events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('events', models.FileField(upload_to='department/CS/data/events/')),
                ('semester', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='mathematics_dept_lab_facilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('qty', models.IntegerField()),
                ('config_specs', models.TextField()),
                ('softwares', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='mathematics_dept_laboratory_facilities_gallary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='department/gallery/CS/laboratory/')),
            ],
        ),
        migrations.CreateModel(
            name='mathematics_dept_major_equipments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='mathematics_dept_publications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_faculty', models.CharField(max_length=100)),
                ('y15', models.IntegerField(blank=True, null=True)),
                ('y16', models.IntegerField(blank=True, null=True)),
                ('y17', models.IntegerField(blank=True, null=True)),
                ('y18', models.IntegerField(blank=True, null=True)),
                ('y19', models.IntegerField(blank=True, null=True)),
                ('national_or_inter', models.CharField(max_length=13)),
                ('indexing', models.CharField(blank=True, max_length=500, null=True)),
                ('citations', models.IntegerField(blank=True, null=True)),
                ('impact_factor', models.CharField(blank=True, max_length=80, null=True)),
                ('i10_index', models.IntegerField(blank=True, null=True)),
                ('h_index', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='mathematics_dept_research_guide',
            fields=[
                ('sno', models.IntegerField(primary_key=True, serialize=False)),
                ('guide_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='mathematics_dept_timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(choices=[('BE', 'B.E.'), ('MT', 'M.Tech')], default='BE', max_length=100)),
                ('semester', models.IntegerField()),
                ('section', models.CharField(max_length=1)),
                ('timetable', models.FileField(upload_to='department/CS/data/timetable/')),
            ],
        ),
        migrations.CreateModel(
            name='mechanical_dept_achievements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_description', models.TextField()),
                ('achievement_type', models.CharField(choices=[('STUDENT', 'Student Achievement'), ('STAFF', 'Staff Achievement')], default='STAFF', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='mechanical_dept_activities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('activity_name', models.CharField(max_length=200)),
                ('activity_description', models.TextField()),
                ('activity_type', models.CharField(choices=[('RE', 'Regular Event'), ('STC', 'Short-term Course')], default='RE', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='mechanical_dept_book_chapters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_no', models.IntegerField()),
                ('name_of_book_chapter', models.CharField(max_length=500)),
                ('names_of_authors', models.CharField(max_length=500)),
                ('year_of_pub', models.IntegerField()),
                ('name_of_pub', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='mechanical_dept_classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.FileField(upload_to='department/CS/data/classroom/')),
            ],
        ),
        migrations.CreateModel(
            name='mechanical_dept_events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('events', models.FileField(upload_to='department/CS/data/events/')),
                ('semester', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='mechanical_dept_lab_facilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('qty', models.IntegerField()),
                ('config_specs', models.TextField()),
                ('softwares', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='mechanical_dept_laboratory_facilities_gallary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='department/gallery/CS/laboratory/')),
            ],
        ),
        migrations.CreateModel(
            name='mechanical_dept_major_equipments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='mechanical_dept_publications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_faculty', models.CharField(max_length=100)),
                ('y15', models.IntegerField(blank=True, null=True)),
                ('y16', models.IntegerField(blank=True, null=True)),
                ('y17', models.IntegerField(blank=True, null=True)),
                ('y18', models.IntegerField(blank=True, null=True)),
                ('y19', models.IntegerField(blank=True, null=True)),
                ('national_or_inter', models.CharField(max_length=13)),
                ('indexing', models.CharField(blank=True, max_length=500, null=True)),
                ('citations', models.IntegerField(blank=True, null=True)),
                ('impact_factor', models.CharField(blank=True, max_length=80, null=True)),
                ('i10_index', models.IntegerField(blank=True, null=True)),
                ('h_index', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='mechanical_dept_research_guide',
            fields=[
                ('sno', models.IntegerField(primary_key=True, serialize=False)),
                ('guide_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='mechanical_dept_timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(choices=[('BE', 'B.E.'), ('MT', 'M.Tech')], default='BE', max_length=100)),
                ('semester', models.IntegerField()),
                ('section', models.CharField(max_length=1)),
                ('timetable', models.FileField(upload_to='department/CS/data/timetable/')),
            ],
        ),
        migrations.CreateModel(
            name='physics_dept_achievements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_description', models.TextField()),
                ('achievement_type', models.CharField(choices=[('STUDENT', 'Student Achievement'), ('STAFF', 'Staff Achievement')], default='STAFF', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='physics_dept_activities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('activity_name', models.CharField(max_length=200)),
                ('activity_description', models.TextField()),
                ('activity_type', models.CharField(choices=[('RE', 'Regular Event'), ('STC', 'Short-term Course')], default='RE', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='physics_dept_book_chapters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_no', models.IntegerField()),
                ('name_of_book_chapter', models.CharField(max_length=500)),
                ('names_of_authors', models.CharField(max_length=500)),
                ('year_of_pub', models.IntegerField()),
                ('name_of_pub', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='physics_dept_classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.FileField(upload_to='department/CS/data/classroom/')),
            ],
        ),
        migrations.CreateModel(
            name='physics_dept_events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('events', models.FileField(upload_to='department/CS/data/events/')),
                ('semester', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='physics_dept_lab_facilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('qty', models.IntegerField()),
                ('config_specs', models.TextField()),
                ('softwares', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='physics_dept_laboratory_facilities_gallary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='department/gallery/CS/laboratory/')),
            ],
        ),
        migrations.CreateModel(
            name='physics_dept_major_equipments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='physics_dept_publications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_faculty', models.CharField(max_length=100)),
                ('y15', models.IntegerField(blank=True, null=True)),
                ('y16', models.IntegerField(blank=True, null=True)),
                ('y17', models.IntegerField(blank=True, null=True)),
                ('y18', models.IntegerField(blank=True, null=True)),
                ('y19', models.IntegerField(blank=True, null=True)),
                ('national_or_inter', models.CharField(max_length=13)),
                ('indexing', models.CharField(blank=True, max_length=500, null=True)),
                ('citations', models.IntegerField(blank=True, null=True)),
                ('impact_factor', models.CharField(blank=True, max_length=80, null=True)),
                ('i10_index', models.IntegerField(blank=True, null=True)),
                ('h_index', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='physics_dept_research_guide',
            fields=[
                ('sno', models.IntegerField(primary_key=True, serialize=False)),
                ('guide_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='physics_dept_timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(choices=[('BE', 'B.E.'), ('MT', 'M.Tech')], default='BE', max_length=100)),
                ('semester', models.IntegerField()),
                ('section', models.CharField(max_length=1)),
                ('timetable', models.FileField(upload_to='department/CS/data/timetable/')),
            ],
        ),
        migrations.CreateModel(
            name='physics_dept_research_scholars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_scholar_name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('year_of_regn', models.IntegerField(choices=[(1979, 1979), (1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (0, 'NA')], default=0)),
                ('phD', models.CharField(choices=[('PHD', 'Ph.D.'), ('(PHD)', '(Ph.D.)')], default='(PHD)', max_length=10)),
                ('course_work_completed', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1)),
                ('pre_phD_viva_voce', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1)),
                ('submitted_final_thesis', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1)),
                ('phD_awarded_year', models.IntegerField(choices=[(1979, 1979), (1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (0, 'NA')], default=0)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.computer_science_dept_research_guide')),
            ],
        ),
        migrations.CreateModel(
            name='mechanical_dept_research_scholars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_scholar_name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('year_of_regn', models.IntegerField(choices=[(1979, 1979), (1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (0, 'NA')], default=0)),
                ('phD', models.CharField(choices=[('PHD', 'Ph.D.'), ('(PHD)', '(Ph.D.)')], default='(PHD)', max_length=10)),
                ('course_work_completed', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1)),
                ('pre_phD_viva_voce', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1)),
                ('submitted_final_thesis', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1)),
                ('phD_awarded_year', models.IntegerField(choices=[(1979, 1979), (1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (0, 'NA')], default=0)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.computer_science_dept_research_guide')),
            ],
        ),
        migrations.CreateModel(
            name='mathematics_dept_research_scholars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_scholar_name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('year_of_regn', models.IntegerField(choices=[(1979, 1979), (1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (0, 'NA')], default=0)),
                ('phD', models.CharField(choices=[('PHD', 'Ph.D.'), ('(PHD)', '(Ph.D.)')], default='(PHD)', max_length=10)),
                ('course_work_completed', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1)),
                ('pre_phD_viva_voce', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1)),
                ('submitted_final_thesis', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1)),
                ('phD_awarded_year', models.IntegerField(choices=[(1979, 1979), (1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (0, 'NA')], default=0)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.computer_science_dept_research_guide')),
            ],
        ),
        migrations.CreateModel(
            name='civil_dept_research_scholars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_scholar_name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('year_of_regn', models.IntegerField(choices=[(1979, 1979), (1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (0, 'NA')], default=0)),
                ('phD', models.CharField(choices=[('PHD', 'Ph.D.'), ('(PHD)', '(Ph.D.)')], default='(PHD)', max_length=10)),
                ('course_work_completed', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1)),
                ('pre_phD_viva_voce', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1)),
                ('submitted_final_thesis', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1)),
                ('phD_awarded_year', models.IntegerField(choices=[(1979, 1979), (1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (0, 'NA')], default=0)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.computer_science_dept_research_guide')),
            ],
        ),
        migrations.CreateModel(
            name='chemistry_dept_research_scholars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_scholar_name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('year_of_regn', models.IntegerField(choices=[(1979, 1979), (1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (0, 'NA')], default=0)),
                ('phD', models.CharField(choices=[('PHD', 'Ph.D.'), ('(PHD)', '(Ph.D.)')], default='(PHD)', max_length=10)),
                ('course_work_completed', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1)),
                ('pre_phD_viva_voce', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1)),
                ('submitted_final_thesis', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1)),
                ('phD_awarded_year', models.IntegerField(choices=[(1979, 1979), (1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (0, 'NA')], default=0)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.computer_science_dept_research_guide')),
            ],
        ),
    ]
