# Generated by Django 3.0.6 on 2020-06-20 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0025_chemistry_dept_achievements_chemistry_dept_activities_chemistry_dept_book_chapters_chemistry_dept_cl'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='civil_depatment_gallery',
            new_name='civil_dept_gallery',
        ),
    ]
