# Generated by Django 3.0.6 on 2020-06-22 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0028_bio_medical_dept_alumni_bio_technology_dept_alumni_chemical_dept_alumni_civil_dept_alumni_computer_s'),
    ]

    operations = [
        migrations.CreateModel(
            name='bio_medical_dept_grants_and_patents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('grant_or_patent', models.CharField(choices=[('GRANT', 'Grant'), ('PATENT', 'Patent')], default='GRANT', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='bio_technology_dept_grants_and_patents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('grant_or_patent', models.CharField(choices=[('GRANT', 'Grant'), ('PATENT', 'Patent')], default='GRANT', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='chemical_dept_grants_and_patents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('grant_or_patent', models.CharField(choices=[('GRANT', 'Grant'), ('PATENT', 'Patent')], default='GRANT', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='chemistry_dept_grants_and_patents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('grant_or_patent', models.CharField(choices=[('GRANT', 'Grant'), ('PATENT', 'Patent')], default='GRANT', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='civil_dept_grants_and_patents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('grant_or_patent', models.CharField(choices=[('GRANT', 'Grant'), ('PATENT', 'Patent')], default='GRANT', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='computer_science_dept_grants_and_patents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('grant_or_patent', models.CharField(choices=[('GRANT', 'Grant'), ('PATENT', 'Patent')], default='GRANT', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='electrical_and_electronics_dept_grants_and_patents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('grant_or_patent', models.CharField(choices=[('GRANT', 'Grant'), ('PATENT', 'Patent')], default='GRANT', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='electronics_and_communication_dept_grants_and_patents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('grant_or_patent', models.CharField(choices=[('GRANT', 'Grant'), ('PATENT', 'Patent')], default='GRANT', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='electronics_and_instrumentation_dept_grants_and_patents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('grant_or_patent', models.CharField(choices=[('GRANT', 'Grant'), ('PATENT', 'Patent')], default='GRANT', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='information_science_dept_grants_and_patents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('grant_or_patent', models.CharField(choices=[('GRANT', 'Grant'), ('PATENT', 'Patent')], default='GRANT', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='mathematics_dept_grants_and_patents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('grant_or_patent', models.CharField(choices=[('GRANT', 'Grant'), ('PATENT', 'Patent')], default='GRANT', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='mechanical_dept_grants_and_patents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('grant_or_patent', models.CharField(choices=[('GRANT', 'Grant'), ('PATENT', 'Patent')], default='GRANT', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='physics_dept_grants_and_patents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('grant_or_patent', models.CharField(choices=[('GRANT', 'Grant'), ('PATENT', 'Patent')], default='GRANT', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='textile_technology_dept_grants_and_patents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('grant_or_patent', models.CharField(choices=[('GRANT', 'Grant'), ('PATENT', 'Patent')], default='GRANT', max_length=500)),
            ],
        ),
    ]
