# Generated by Django 3.0.6 on 2020-06-24 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0035_auto_20200623_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='bio_medical_dept_learning_materials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField(choices=[(3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)])),
                ('subject_code', models.CharField(max_length=100)),
                ('material', models.FileField(upload_to='department/BM/data/learning-materials')),
            ],
        ),
        migrations.CreateModel(
            name='bio_technology_dept_learning_materials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField(choices=[(3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)])),
                ('subject_code', models.CharField(max_length=100)),
                ('material', models.FileField(upload_to='department/BT/data/learning-materials')),
            ],
        ),
        migrations.CreateModel(
            name='chemical_dept_learning_materials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField(choices=[(3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)])),
                ('subject_code', models.CharField(max_length=100)),
                ('material', models.FileField(upload_to='department/CH/data/learning-materials')),
            ],
        ),
        migrations.CreateModel(
            name='chemistry_dept_learning_materials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField(choices=[(1, 1), (2, 2)])),
                ('subject_code', models.CharField(max_length=100)),
                ('material', models.FileField(upload_to='department/CHEM/data/learning-materials')),
            ],
        ),
        migrations.CreateModel(
            name='civil_dept_learning_materials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField(choices=[(3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)])),
                ('subject_code', models.CharField(max_length=100)),
                ('material', models.FileField(upload_to='department/CV/data/learning-materials')),
            ],
        ),
        migrations.CreateModel(
            name='computer_science_dept_learning_materials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField(choices=[(3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)])),
                ('subject_code', models.CharField(max_length=100)),
                ('material', models.FileField(upload_to='department/CS/data/learning-materials')),
            ],
        ),
        migrations.CreateModel(
            name='electrical_and_electronics_dept_learning_materials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField(choices=[(3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)])),
                ('subject_code', models.CharField(max_length=100)),
                ('material', models.FileField(upload_to='department/EE/data/learning-materials')),
            ],
        ),
        migrations.CreateModel(
            name='electronics_and_communication_dept_learning_materials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField(choices=[(3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)])),
                ('subject_code', models.CharField(max_length=100)),
                ('material', models.FileField(upload_to='department/EC/data/learning-materials')),
            ],
        ),
        migrations.CreateModel(
            name='electronics_and_instrumentation_dept_learning_materials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField(choices=[(3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)])),
                ('subject_code', models.CharField(max_length=100)),
                ('material', models.FileField(upload_to='department/EI/data/learning-materials')),
            ],
        ),
        migrations.CreateModel(
            name='information_science_dept_learning_materials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField(choices=[(3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)])),
                ('subject_code', models.CharField(max_length=100)),
                ('material', models.FileField(upload_to='department/IS/data/learning-materials')),
            ],
        ),
        migrations.CreateModel(
            name='mathematics_dept_learning_materials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)])),
                ('subject_code', models.CharField(max_length=100)),
                ('material', models.FileField(upload_to='department/MAT/data/learning-materials')),
            ],
        ),
        migrations.CreateModel(
            name='mechanical_dept_learning_materials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField(choices=[(3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)])),
                ('subject_code', models.CharField(max_length=100)),
                ('material', models.FileField(upload_to='department/ME/data/learning-materials')),
            ],
        ),
        migrations.CreateModel(
            name='physics_dept_learning_materials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField(choices=[(1, 1), (2, 2)])),
                ('subject_code', models.CharField(max_length=100)),
                ('material', models.FileField(upload_to='department/PHY/data/learning-materials')),
            ],
        ),
        migrations.CreateModel(
            name='textile_technology_dept_learning_materials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField(choices=[(3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)])),
                ('subject_code', models.CharField(max_length=100)),
                ('material', models.FileField(upload_to='department/TX/data/learning-materials')),
            ],
        ),
    ]
