# Generated by Django 2.2 on 2019-10-24 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reports', models.FileField(upload_to='facilities/Sport/')),
            ],
        ),
    ]
