# Generated by Django 2.2 on 2019-10-04 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField()),
                ('venue', models.CharField(max_length=200)),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
            ],
        ),
    ]
