# Generated by Django 2.2 on 2019-10-04 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.CharField(max_length=200),
        ),
    ]
