# Generated by Django 2.2 on 2019-10-23 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_web', '0005_auto_20191005_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GallaryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='main_gallary')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallary', to='main_web.Gallary')),
            ],
        ),
    ]
