# Generated by Django 2.2 on 2019-10-23 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_web', '0007_auto_20191023_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images_1', models.ImageField(upload_to='main_gallary')),
                ('images_2', models.ImageField(upload_to='main_gallary')),
                ('images_3', models.ImageField(upload_to='main_gallary')),
                ('images_4', models.ImageField(upload_to='main_gallary')),
            ],
        ),
    ]
