# Generated by Django 2.2 on 2019-10-23 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_web', '0008_gallary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallary',
            name='images_1',
            field=models.ImageField(null=True, upload_to='main_gallary'),
        ),
        migrations.AlterField(
            model_name='gallary',
            name='images_2',
            field=models.ImageField(null=True, upload_to='main_gallary'),
        ),
        migrations.AlterField(
            model_name='gallary',
            name='images_3',
            field=models.ImageField(null=True, upload_to='main_gallary'),
        ),
        migrations.AlterField(
            model_name='gallary',
            name='images_4',
            field=models.ImageField(null=True, upload_to='main_gallary'),
        ),
    ]
