# Generated by Django 2.2 on 2019-10-23 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_web', '0009_auto_20191023_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallary',
            name='images_1',
            field=models.ImageField(blank=True, null=True, upload_to='main_gallary'),
        ),
        migrations.AlterField(
            model_name='gallary',
            name='images_2',
            field=models.ImageField(blank=True, null=True, upload_to='main_gallary'),
        ),
        migrations.AlterField(
            model_name='gallary',
            name='images_3',
            field=models.ImageField(blank=True, null=True, upload_to='main_gallary'),
        ),
        migrations.AlterField(
            model_name='gallary',
            name='images_4',
            field=models.ImageField(blank=True, null=True, upload_to='main_gallary'),
        ),
    ]
