# Generated by Django 2.2 on 2019-10-23 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_web', '0010_auto_20191023_1323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallary',
            old_name='images_1',
            new_name='images',
        ),
        migrations.RemoveField(
            model_name='gallary',
            name='images_2',
        ),
        migrations.RemoveField(
            model_name='gallary',
            name='images_3',
        ),
        migrations.RemoveField(
            model_name='gallary',
            name='images_4',
        ),
    ]
