# Generated by Django 2.2 on 2019-10-24 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pg_addmission',
            name='notification',
            field=models.FileField(blank='', upload_to='addmission/PG/'),
        ),
    ]
