# Generated by Django 2.2 on 2019-10-24 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0005_auto_20191024_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pg_addmission',
            name='cut_off',
            field=models.FileField(default='coming-soon.png', upload_to='addmission/PG/'),
        ),
        migrations.AlterField(
            model_name='pg_addmission',
            name='notification',
            field=models.FileField(default='coming-soon.png', upload_to='addmission/PG/'),
        ),
    ]
