# Generated by Django 2.2 on 2019-11-02 04:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0006_auto_20191024_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='ug_addmission',
            name='new_file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='addmission/UG/'),
            preserve_default=False,
        ),
    ]
