# Generated by Django 2.2 on 2019-11-02 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0007_ug_addmission_new_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ug_addmission',
            name='new_file',
        ),
    ]
