# Generated by Django 2.2 on 2019-10-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_life', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NAAC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brochure', models.FileField(upload_to='campus_life/NAAC/')),
            ],
        ),
    ]
