# Generated by Django 2.2 on 2020-05-29 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_life', '0002_naac'),
    ]

    operations = [
        migrations.CreateModel(
            name='btech_technowav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btech_technowav', models.FileField(upload_to='campus_life/btech_technowav/')),
            ],
        ),
    ]
