# Generated by Django 2.2 on 2020-05-29 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_biet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office_Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='about_biet/office/image/')),
                ('detail', models.FileField(upload_to='department/office/data/')),
                ('sno', models.IntegerField()),
            ],
        ),
    ]
