# Generated by Django 2.2 on 2020-05-30 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_biet', '0002_office_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='EOA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eoa', models.FileField(upload_to='about_biet/eoa/')),
            ],
        ),
    ]
