# Generated by Django 3.0.6 on 2020-07-03 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_biet', '0003_eoa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EOA',
        ),
    ]
