# Generated by Django 3.0.6 on 2020-07-03 13:09

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('about_biet', '0004_delete_eoa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('responsibility', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('contact_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('image', models.ImageField(upload_to='about_biet/deans/image/')),
                ('description', models.TextField()),
                ('detail', models.FileField(upload_to='about_biet/deans/data/')),
            ],
        ),
        migrations.AlterField(
            model_name='office_staff',
            name='detail',
            field=models.FileField(upload_to='about_biet/office/data/'),
        ),
    ]
