# Generated by Django 3.0.6 on 2020-07-03 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_biet', '0005_auto_20200703_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='Governing_Body',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
            ],
        ),
    ]
