# Generated by Django 3.0.6 on 2020-07-06 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_biet', '0007_governing_body_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Governing_Council',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('image', models.ImageField(default='', upload_to='about_biet/governing_council/image/')),
            ],
        ),
    ]
