from django.contrib import admin
from .models import civil_dept, mechanical_dept, biotechnology_dept, chemical_dept, chemistry_dept
from .models import computer_science_dept, electronics_and_communication_dept, electrical_and_electronics_dept
from .models import information_science_dept, mathematics_dept, physics_dept, textile_dept, mca_dept, environmental_dept
from .models import civil_depatment_gallery, mechanical_dept_gallery, biotechnology_dept_gallery, chemical_dept_gallery
from .models import chemistry_dept_gallery, computer_science_dept_gallery, electronics_and_communication_gallery
from .models import electrical_and_electronics_gallery, information_science_dept_gallery, mathematics_dept_gallery
from .models import physics_dept_gallery, textile_dept_gallery, mca_dept_gallery, environmental_dept_gallery
from .models import computer_science_dept_lab_facilities, computer_science_dept_major_equipments, computer_science_dept_activities
from .models import computer_science_dept_classroom,computer_science_dept_events
from .models import computer_science_dept_achievements, computer_science_dept_timetable
from .models import computer_science_dept_research_scholars, computer_science_dept_research_guide,computer_science_dept_laboratory_facilities_gallary
from .models import computer_science_dept_book_chapters, computer_science_dept_publications, computer_science_dept_accreditation
from .models import information_science_dept_lab_facilities, information_science_dept_major_equipments, information_science_dept_activities
from .models import information_science_dept_classroom,information_science_dept_events
from .models import information_science_dept_achievements, information_science_dept_timetable
from .models import information_science_dept_research_scholars, information_science_dept_research_guide,information_science_dept_laboratory_facilities_gallary
from .models import information_science_dept_book_chapters, information_science_dept_publications, information_science_dept_accreditation
from .models import electrical_and_electronics_dept_lab_facilities, electrical_and_electronics_dept_major_equipments, electrical_and_electronics_dept_activities
from .models import electrical_and_electronics_dept_classroom,electrical_and_electronics_dept_events
from .models import electrical_and_electronics_dept_achievements, electrical_and_electronics_dept_timetable
from .models import electrical_and_electronics_dept_research_scholars, electrical_and_electronics_dept_research_guide,electrical_and_electronics_dept_laboratory_facilities_gallary
from .models import electrical_and_electronics_dept_book_chapters, electrical_and_electronics_dept_publications, electrical_and_electronics_dept_accreditation
from .models import electronics_and_communication_dept_lab_facilities, electronics_and_communication_dept_major_equipments, electronics_and_communication_dept_activities
from .models import electronics_and_communication_dept_classroom,electronics_and_communication_dept_events
from .models import electronics_and_communication_dept_achievements, electronics_and_communication_dept_timetable
from .models import electronics_and_communication_dept_research_scholars, electronics_and_communication_dept_research_guide,electronics_and_communication_dept_laboratory_facilities_gallary
from .models import electronics_and_communication_dept_book_chapters, electronics_and_communication_dept_publications, electronics_and_communication_dept_accreditation
from .models import biotechnology_dept_lab_facilities, biotechnology_dept_major_equipments, biotechnology_dept_activities
from .models import biotechnology_dept_classroom,biotechnology_dept_events
from .models import biotechnology_dept_achievements, biotechnology_dept_timetable
from .models import biotechnology_dept_research_scholars, biotechnology_dept_research_guide,biotechnology_dept_laboratory_facilities_gallary
from .models import biotechnology_dept_book_chapters, biotechnology_dept_publications, biotechnology_dept_accreditation
from .models import mca_dept_lab_facilities, mca_dept_major_equipments, mca_dept_activities
from .models import mca_dept_classroom,mca_dept_events
from .models import mca_dept_achievements, mca_dept_timetable
from .models import mca_dept_research_scholars, mca_dept_research_guide,mca_dept_laboratory_facilities_gallary
from .models import mca_dept_book_chapters, mca_dept_publications, mca_dept_accreditation
from .models import environmental_dept_lab_facilities, environmental_dept_major_equipments, environmental_dept_activities
from .models import environmental_dept_classroom,environmental_dept_events
from .models import environmental_dept_achievements, environmental_dept_timetable
from .models import environmental_dept_research_scholars, environmental_dept_research_guide,environmental_dept_laboratory_facilities_gallary
from .models import environmental_dept_book_chapters, environmental_dept_publications, environmental_dept_accreditation
# Register your models here.
admin.site.register(civil_dept)
admin.site.register(mechanical_dept)
admin.site.register(biotechnology_dept)
admin.site.register(chemical_dept)
admin.site.register(chemistry_dept)
admin.site.register(computer_science_dept)
admin.site.register(electronics_and_communication_dept)
admin.site.register(electrical_and_electronics_dept)
admin.site.register(information_science_dept)
admin.site.register(mathematics_dept)
admin.site.register(physics_dept)
admin.site.register(textile_dept)
admin.site.register(mca_dept)
admin.site.register(environmental_dept)
admin.site.register(civil_depatment_gallery)
admin.site.register(mechanical_dept_gallery)
admin.site.register(biotechnology_dept_gallery)
admin.site.register(chemical_dept_gallery)
admin.site.register(chemistry_dept_gallery)
admin.site.register(computer_science_dept_gallery)
admin.site.register(electronics_and_communication_gallery)
admin.site.register(electrical_and_electronics_gallery)
admin.site.register(information_science_dept_gallery)
admin.site.register(mathematics_dept_gallery)
admin.site.register(physics_dept_gallery)
admin.site.register(textile_dept_gallery)
admin.site.register(mca_dept_gallery)
admin.site.register(environmental_dept_gallery)
admin.site.register(computer_science_dept_lab_facilities)
admin.site.register(computer_science_dept_major_equipments)
admin.site.register(computer_science_dept_activities)
admin.site.register(computer_science_dept_achievements)
admin.site.register(computer_science_dept_timetable)
admin.site.register(computer_science_dept_events)
admin.site.register(computer_science_dept_classroom)
admin.site.register(computer_science_dept_research_scholars)
admin.site.register(computer_science_dept_research_guide)
admin.site.register(computer_science_dept_laboratory_facilities_gallary)
admin.site.register(computer_science_dept_publications)
admin.site.register(computer_science_dept_book_chapters)
admin.site.register(computer_science_dept_accreditation)
admin.site.register(information_science_dept_lab_facilities)
admin.site.register(information_science_dept_major_equipments)
admin.site.register(information_science_dept_activities)
admin.site.register(information_science_dept_achievements)
admin.site.register(information_science_dept_timetable)
admin.site.register(information_science_dept_events)
admin.site.register(information_science_dept_classroom)
admin.site.register(information_science_dept_research_scholars)
admin.site.register(information_science_dept_research_guide)
admin.site.register(information_science_dept_laboratory_facilities_gallary)
admin.site.register(information_science_dept_publications)
admin.site.register(information_science_dept_book_chapters)
admin.site.register(information_science_dept_accreditation)
admin.site.register(electrical_and_electronics_dept_lab_facilities)
admin.site.register(electrical_and_electronics_dept_major_equipments)
admin.site.register(electrical_and_electronics_dept_activities)
admin.site.register(electrical_and_electronics_dept_achievements)
admin.site.register(electrical_and_electronics_dept_timetable)
admin.site.register(electrical_and_electronics_dept_events)
admin.site.register(electrical_and_electronics_dept_classroom)
admin.site.register(electrical_and_electronics_dept_research_scholars)
admin.site.register(electrical_and_electronics_dept_research_guide)
admin.site.register(electrical_and_electronics_dept_laboratory_facilities_gallary)
admin.site.register(electrical_and_electronics_dept_publications)
admin.site.register(electrical_and_electronics_dept_book_chapters)
admin.site.register(electrical_and_electronics_dept_accreditation)
admin.site.register(electronics_and_communication_dept_lab_facilities)
admin.site.register(electronics_and_communication_dept_major_equipments)
admin.site.register(electronics_and_communication_dept_activities)
admin.site.register(electronics_and_communication_dept_achievements)
admin.site.register(electronics_and_communication_dept_timetable)
admin.site.register(electronics_and_communication_dept_events)
admin.site.register(electronics_and_communication_dept_classroom)
admin.site.register(electronics_and_communication_dept_research_scholars)
admin.site.register(electronics_and_communication_dept_research_guide)
admin.site.register(electronics_and_communication_dept_laboratory_facilities_gallary)
admin.site.register(electronics_and_communication_dept_publications)
admin.site.register(electronics_and_communication_dept_book_chapters)
admin.site.register(electronics_and_communication_dept_accreditation)
admin.site.register(biotechnology_dept_lab_facilities)
admin.site.register(biotechnology_dept_major_equipments)
admin.site.register(biotechnology_dept_activities)
admin.site.register(biotechnology_dept_achievements)
admin.site.register(biotechnology_dept_timetable)
admin.site.register(biotechnology_dept_events)
admin.site.register(biotechnology_dept_classroom)
admin.site.register(biotechnology_dept_research_scholars)
admin.site.register(biotechnology_dept_research_guide)
admin.site.register(biotechnology_dept_laboratory_facilities_gallary)
admin.site.register(biotechnology_dept_publications)
admin.site.register(biotechnology_dept_book_chapters)
admin.site.register(biotechnology_dept_accreditation)
admin.site.register(mca_dept_lab_facilities)
admin.site.register(mca_dept_major_equipments)
admin.site.register(mca_dept_activities)
admin.site.register(mca_dept_achievements)
admin.site.register(mca_dept_timetable)
admin.site.register(mca_dept_events)
admin.site.register(mca_dept_classroom)
admin.site.register(mca_dept_research_scholars)
admin.site.register(mca_dept_research_guide)
admin.site.register(mca_dept_laboratory_facilities_gallary)
admin.site.register(mca_dept_publications)
admin.site.register(mca_dept_book_chapters)
admin.site.register(mca_dept_accreditation)
admin.site.register(environmental_dept_lab_facilities)
admin.site.register(environmental_dept_major_equipments)
admin.site.register(environmental_dept_activities)
admin.site.register(environmental_dept_achievements)
admin.site.register(environmental_dept_timetable)
admin.site.register(environmental_dept_events)
admin.site.register(environmental_dept_classroom)
admin.site.register(environmental_dept_research_scholars)
admin.site.register(environmental_dept_research_guide)
admin.site.register(environmental_dept_laboratory_facilities_gallary)
admin.site.register(environmental_dept_publications)
admin.site.register(environmental_dept_book_chapters)
admin.site.register(environmental_dept_accreditation)